name: Deploy Maria Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0

        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}

          script: |
            echo "🚀 Déploiement..."

            cd ${{ secrets.VPS_PATH }}

            # 🔥 FIX: clone si repo absent
            if [ ! -d ".git" ]; then
              echo "📥 Clone du projet..."
              git clone https://github.com/MANGA-BOT/kira-md.git .
            else
              echo "📥 Mise à jour du code..."
              git pull origin main
            fi

            echo "📦 Installation des dépendances..."
            npm install

            echo "⚡ Gestion PM2..."

            pm2 describe kira-md > /dev/null
            if [ $? -eq 0 ]; then
              echo "🔄 Restart bot"
              pm2 restart kira-md
            else
              echo "🆕 Démarrage bot"
              pm2 start index.js --name kira-md
            fi

            pm2 save

            echo "✅ Deploy terminé"
